[package]
name = "pong"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]

[dependencies.amethyst]
version = "0.11.0"
features = ["vulkan"]

[features]
empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
vulkan = ["amethyst/vulkan"]
